### ISSUE TITLE
Ignore required words for t411

### ISSUE THREAD

**Issue by stven** [mozvip/CouchPotatoServer#1]
For international providers, i've setup some "required words" such that "french"...
Obviously, T411 only return french results but "french" isn't systematically in the file name.
So it would be great if we could choose an option such that "ignore required words for t411".

**Comment by an0Nym0us63** [comment]
I added french in the title for each results returned by t411.
So it isnt a problem if its not on the title

Envoyé de mon iPhone

**Comment by stven** [comment]
OK perfect!
I was still with the file of brinbois.

**Comment by an0Nym0us63** [comment]
yes ok id did that as i noticed the files were rejected when required french was used.

I will be more precise by using vostfr and vo and append different words

But for now you can just add VOSTFR to the ignore words as for those vostfr is present in the titlte but the scraper will still append french to it
but i will be more precise in the scraper for that.
