### ISSUE TITLE
Impossible de renseigner les dossiers de réceptions

### ISSUE THREAD

**Issue by nahsiy** [mozvip/CouchPotatoServer#12]
Bonjour,
J'espère que le fait que je m'exprime en français ne vous dérange pas trop. Je me permet de le faire car, tout d'abord je ne maitrise pas vraiment la langue de Shakespeare et ensuite le projet est un fork Fr.

Sous windows 7, branch developer, je ne peux renseigner/ pointer les dossiers de réceptions de mes torrents.
De plus, dans l'onglet HOME, il n'apparait pas la fonction 'suggestions de films'.
Enfin, j'ai l'impression que la fonction 'recherche' n'est pas aussi efficace, complète, opérationnelle que sur le projet initial.

Voilà mon retour global.
Merci en tout cas pour ce fabuleux outil.

Librement,
Aissa

EDIT : j'aimerai bien pouvoir obtenir le mail de sarakha63 afin de proceder à une donation.

**Comment by an0Nym0us63** [comment]
mauvais git la suite de ce projet est sur le git sarakha63

**Comment by nahsiy** [comment]
Merci pour ce retour @sarakha63 . Je clos ce ticket 10 ans après :)
