### ISSUE TITLE
T411

### ISSUE THREAD

**Issue by bidulle95** [mozvip/CouchPotatoServer#20]
bonjour j'ai une erreur 403 avec t411 
suis le seul?
[se.providers.torrent.t411] Login to T411 failed: HTTP Error 403: Acc&#232;s refus&#233;

**Comment by mozvip** [comment]
Hello,

Ben je crois surtout que tu es le seul à utiliser encore ce fork !!!

**Comment by bidulle95** [comment]
non je suis sur le fork de cyberden mais ca ma rabattu sur ce fork on peut pas faire d'issue sur l'autre
