### ISSUE TITLE
Movie Manager

### ISSUE THREAD

**Issue by Nonobis** [mozvip/CouchPotatoServer#9]
Salut,

Petite question concernant le Movie Manager.

J'utilise la version git sous windows (depuis les sources) avec tous ce qu'il faut d'après la sources officiel et les divers post du forum.

J'ai ajouté le chemin vers le répertoire de mon nas en "\DS411\Video\Films".
Mon répertoire "Films" est composé d'un répertoire par film, le film en mp4 et j'ai les fichiers nfo, poster etc au format xbmc.

Par contre que cela soit sous chrome ou firefox j'ai beau cliqué sur le bouton.
Je n'obtiens jamais un films dans la liste des films détecté.

Y'a t'il une solution de votre coté ? Je peut voir pour founir le fichier de log si besoin ou ma config.

**Comment by an0Nym0us63** [comment]
je doute fort que /DS411/balbnalba marche sous windows.

Je te conseil de monter un lecteur reseau pour ce repertoire du genre lettre X et de declarer ce repertoire dans couch

**Comment by Nonobis** [comment]
En fait, j'ai bien des lecteurs réseaux mais ceux ci n'apparaisse pas dans l'interface de couchpotato.
en les rajoutant manuellement sous le ini je n'ai pas l'impression d'avoir de prise en comtpe non plus.

**Comment by an0Nym0us63** [comment]
Alors ca doit etre un bug du couch officiel je pense. 

---

De: Nonobis 
Envoyé: mer., 15/05/2013 11:25
A: mozvip/CouchPotatoServer CouchPotatoServer@noreply.github.com
CC: sarakha63 sarakha_ludovic@yahoo.fr
Objet: Re: [CouchPotatoServer] Movie Manager (#9)

**Comment by Nonobis** [comment]
Je suis au taff mais je peut tenter en faisant un test avec teamviewer. Est-ce que les logs pourrait t'aider ou vaudrait'il mieux que je renvoie cela sur l'officiel ?
